name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Dockerfile'
      - 'VERSION'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Dockerfile'
      - 'VERSION'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Read the version
      id: version
      run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

    # 1) Set up or update QEMU to emulate ARM64 more reliably
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        image: tonistiigi/binfmt:latest
        platforms: all

    # 2) Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # 3) Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push multi arch image
      run: |
        docker buildx build \
          --platform linux/amd64,linux/arm64 \
          --push \
          --tag raikaustubh/rahasya:${{ env.VERSION }} \
          --tag raikaustubh/rahasya:latest \
          .
